import type { WordItem } from '../../types/word'

export const emojiByWord: Record<string, string> = {
  animal: '🐾',
  bear: '🐻',
  bee: '🐝',
  bird: '🐦',
  cat: '🐱',
  chicken: '🐔',
  cow: '🐄',
  crocodile: '🐊',
  dog: '🐶',
  donkey: '🫏',
  duck: '🦆',
  elephant: '🐘',
  fish: '🐟',
  fox: '🦊',
  frog: '🐸',
  giraffe: '🦒',
  goat: '🐐',
  hippo: '🦛',
  horse: '🐴',
  lizard: '🦎',
  monkey: '🐵',
  mouse: '🐭',
  panda: '🐼',
  pet: '🐾',
  rabbit: '🐰',
  sheep: '🐑',
  snake: '🐍',
  spider: '🕷️',
  tail: '🦚',
  tiger: '🐯',
  zebra: '🦓',
  zoo: '🦁',
  apple: '🍎',
  banana: '🍌',
  bean: '🫘',
  bread: '🍞',
  breakfast: '🥞',
  burger: '🍔',
  cake: '🍰',
  candy: '🍬',
  carrot: '🥕',
  chips: '🍟',
  chocolate: '🍫',
  coconut: '🥥',
  dinner: '🍽️',
  drink: '🥤',
  egg: '🥚',
  food: '🍱',
  fruit: '🍓',
  grape: '🍇',
  'ice cream': '🍦',
  juice: '🧃',
  lunch: '🥪',
  meat: '🍖',
  meatballs: '🍡',
  milk: '🥛',
  oil: '🫗',
  pear: '🍐',
  pork: '🥩',
  potato: '🥔',
  rice: '🍚',
  sandwich: '🥪',
  sausage: '🌭',
  soup: '🍲',
  sugar: '🍚',
  sweet: '🍭',
  tomato: '🍅',
  vegetable: '🥦',
  water: '💧',
  alphabet: '🔤',
  answer: '💬',
  ask: '❓',
  board: '🟩',
  book: '📘',
  bookcase: '🗄️',
  class: '👩‍🏫',
  classroom: '🏫',
  close: '🔒',
  colour: '🎨',
  computer: '💻',
  correct: '✅',
  crayon: '🖍️',
  desk: '🪑',
  draw: '✍️',
  english: '🇬🇧',
  eraser: '🩹',
  example: '📝',
  find: '🔎',
  floor: '🟫',
  keyboard: '⌨️',
  learn: '📚',
  lesson: '📖',
  letter: '🔠',
  library: '📚',
  line: '📏',
  listen: '👂',
  look: '👀',
  music: '🎵',
  number: '🔢',
  open: '📂',
  page: '📄',
  paint: '🖌️',
  painting: '🖼️',
  paper: '📄',
  pen: '🖊️',
  pencil: '✏️',
  picture: '🖼️',
  playground: '🛝',
  practice: '🔁',
  read: '📖',
  ruler: '📏',
  school: '🏫',
  sentence: '💬',
  spell: '🔡',
  student: '🧒',
  study: '📝',
  teacher: '🧑‍🏫',
  test: '📝',
  word: '🔤',
  write: '✍️',
  apartment: '🏢',
  armchair: '🛋️',
  bath: '🛁',
  bathroom: '🚿',
  bed: '🛏️',
  bedroom: '🛏️',
  box: '📦',
  chair: '🪑',
  clock: '🕒',
  cupboard: '🗄️',
  'dining room': '🍽️',
  door: '🚪',
  furniture: '🪑',
  garage: '🚗',
  garden: '🌷',
  house: '🏠',
  kitchen: '🍳',
  lamp: '💡',
  lift: '🛗',
  'living room': '🛋️',
  mirror: '🪞',
  office: '🏢',
  plant: '🪴',
  pool: '🏊',
  room: '🚪',
  sofa: '🛋️',
  staircase: '🪜',
  table: '🪑',
  towel: '🧻',
  tower: '🗼',
  wall: '🧱',
  window: '🪟',
  ambulance: '🚑',
  bike: '🚲',
  boat: '⛵',
  bus: '🚌',
  car: '🚗',
  coach: '🚌',
  helicopter: '🚁',
  lorry: '🚛',
  motorbike: '🏍️',
  plane: '✈️',
  ship: '🚢',
  taxi: '🚕',
  tractor: '🚜',
  train: '🚆',
  truck: '🚚',
  cloud: '☁️',
  cloudy: '🌥️',
  rain: '🌧️',
  rainy: '☔',
  snow: '❄️',
  snowy: '☃️',
  sun: '☀️',
  sunny: '🌞',
  warm: '🧣',
  weather: '🌤️',
  wind: '💨',
  windy: '🌬️',
  alien: '👽',
  ball: '⚽',
  balloon: '🎈',
  baseball: '⚾',
  basketball: '🏀',
  'board game': '🎲',
  doll: '🪆',
  football: '⚽',
  game: '🎮',
  kite: '🪁',
  puppet: '🎭',
  ride: '🎢',
  teddy: '🧸',
  toy: '🧩',
  black: '⚫',
  blue: '🔵',
  brown: '🟤',
  baby: '👶',
  boy: '👦',
  brother: '👦',
  child: '🧒',
  classmate: '🧑',
  cousin: '🧑',
  dad: '👨',
  family: '👨‍👩‍👧‍👦',
  father: '👨',
  friend: '🤝',
  girl: '👧',
  grandfather: '👴',
  grandma: '👵',
  grandmother: '👵',
  grandpa: '👴',
  grandparent: '🧓',
  kid: '🧒',
  man: '👨',
  mother: '👩',
  mum: '👩',
  'old person': '🧓',
  parent: '🧑',
  sister: '👧',
  woman: '👩',
  young: '🧒',
  badminton: '🏸',
  bat: '🏏',
  beach: '🏖️',
  bounce: '🏀',
  camera: '📷',
  catch: '🥎',
  drawing: '🎨',
  drive: '🚗',
  enjoy: '😊',
  favourite: '⭐',
  fishing: '🎣',
  fly: '🪁',
  guitar: '🎸',
  hobby: '🧩',
  hockey: '🏑',
  kick: '🦵',
  play: '🎮',
  race: '🏁',
  radio: '📻',
  run: '🏃',
  scooter: '🛴',
  see: '👀',
  sing: '🎤',
  skate: '🛼',
  sport: '🏅',
  swim: '🏊',
  'table tennis': '🏓',
  tennis: '🎾',
  travel: '🧳',
  walk: '🚶',
  watch: '⌚',
  yoga: '🧘',
  monday: '1️⃣',
  tuesday: '2️⃣',
  wednesday: '3️⃣',
  thursday: '4️⃣',
  friday: '5️⃣',
  saturday: '6️⃣',
  sunday: '7️⃣',
  january: '1️⃣',
  february: '2️⃣',
  march: '3️⃣',
  april: '4️⃣',
  may: '5️⃣',
  june: '6️⃣',
  july: '7️⃣',
  august: '8️⃣',
  september: '9️⃣',
  october: '🎃',
  november: '🍁',
  december: '🎄',
  'wake up': '⏰',
  'get dressed': '👕',
  'go to school': '🏫',
  'have lunch': '🥪',
  'clean my teeth': '🪥',
  'have a shower': '🚿',
  'do homework': '📝',
  'go home': '🏠',
  'go to bed': '🛏️',
  spring: '🌸',
  summer: '🏖️',
  autumn: '🍂',
  fall: '🍂',
  winter: '❄️',
  behind: '↩️',
  between: '↔️',
  bookshop: '📚',
  end: '🏁',
  here: '📍',
  in: '📥',
  'in front of': '➡️',
  'next to': '↔️',
  on: '🔝',
  park: '🌳',
  shop: '🛍️',
  store: '🏬',
  street: '🛣️',
  there: '📌',
  under: '⬇️',
  actor: '🎭',
  artist: '🧑‍🎨',
  'business person': '💼',
  chef: '👨‍🍳',
  doctor: '🩺',
  driver: '🚕',
  farmer: '🚜',
  'fire fighter': '🧯',
  judge: '⚖️',
  manager: '📋',
  mechanic: '🔧',
  musician: '🎼',
  newsreader: '📰',
  nurse: '💉',
  painter: '🖌️',
  photographer: '📸',
  pilot: '🧑‍✈️',
  'police officer': '👮',
  reporter: '🎙️',
  scientist: '🔬',
  secretary: '🗂️',
  soldier: '🪖',
  veterinarian: '🐾',
  vet: '🐾',
  gray: '⬜',
  green: '🟢',
  grey: '⬜',
  orange: '🟠',
  pink: '🩷',
  purple: '🟣',
  red: '🔴',
  white: '⚪',
  yellow: '🟡',
}

export function getBuiltInVisualToken(word: WordItem) {
  const normalized = word.visualKey ?? word.normalizedWord
  const direct = emojiByWord[normalized]

  if (direct) {
    return direct
  }

  const topicFallbackMap: Record<string, string> = {
    'family-and-friends': '👨‍👩‍👧‍👦',
    'sports-and-leisure': '🎲',
    'days-of-the-week': '📅',
    months: '🗓️',
    seasons: '🌤️',
    'places-and-directions': '📍',
    work: '💼',
  }

  return topicFallbackMap[word.topic] ?? null
}
